name = "neshandel-bot"
main = "index.js"
compatibility_date = "2026-08-01"

[[kv_namespaces]]
binding = "KV"
id = "81218df778704c32ba02d7405bbd3384"

# ── متغیرهای عادی (غیر محرمانه) - در فایل
[vars]
ALLOWED_USERS = "
981260866, 1381797564 , 1787363335"  # ← آیدی عددی خودت را اینجا بگذار